import Product from "../models/Product.js";
import mongoose from "mongoose";
import { validateProduct } from "../validations/productValidation.js";

const normalize = (p) => ({ ...p.toObject(), id: p.productId });
const productFilter = (id) => mongoose.Types.ObjectId.isValid(id) ? { $or: [{ productId: id }, { _id: id }] } : { productId: id };
export const getProducts = async (req, res) => { try { const rows = await Product.find().sort({ createdAt: -1 }); res.json({ success: true, data: rows.map(normalize) }); } catch (e) { res.status(500).json({ success: false, message: e.message }); } };
export const createProduct = async (req, res) => { try { const { error, value } = validateProduct(req.body); if (error) return res.status(422).json({ success: false, message: error.details.map(d => d.message).join("; ") }); const p = await Product.create({ ...value, productId: value.productId || `HOK-PRD-${Date.now()}` }); res.status(201).json({ success: true, data: normalize(p) }); } catch (e) { res.status(400).json({ success: false, message: e.message }); } };
export const updateProduct = async (req, res) => { try { const existing = await Product.findOne(productFilter(req.params.id)); if (!existing) return res.status(404).json({ success: false, message: "Product not found" }); const { error, value } = validateProduct({ ...existing.toObject(), ...req.body, productId: existing.productId }); if (error) return res.status(422).json({ success: false, message: error.details.map(d => d.message).join("; ") }); const p = await Product.findByIdAndUpdate(existing._id, value, { new: true, runValidators: true }); res.json({ success: true, data: normalize(p) }); } catch (e) { res.status(400).json({ success: false, message: e.message }); } };
export const deleteProduct = async (req, res) => { try { const p = await Product.findOneAndDelete({ $or: [{ productId: req.params.id }, { _id: req.params.id }] }); if (!p) return res.status(404).json({ success: false, message: "Product not found" }); res.json({ success: true }); } catch (e) { res.status(400).json({ success: false, message: e.message }); } };
export const archiveProduct = async (req, res) => { try { const p = await Product.findOneAndUpdate({ $or: [{ productId: req.params.id }, { _id: req.params.id }] }, { status: "Archived", $push: { activityLog: { action: "Product archived", user: req.body.user || "Admin" } } }, { new: true }); if (!p) return res.status(404).json({ success: false, message: "Product not found" }); res.json({ success: true, data: normalize(p) }); } catch (e) { res.status(422).json({ success: false, message: e.message }); } };
export const restoreProduct = async (req, res) => { try { const p = await Product.findOneAndUpdate({ $or: [{ productId: req.params.id }, { _id: req.params.id }] }, { status: "Review", $push: { activityLog: { action: "Product restored for review", user: req.body.user || "Admin" } } }, { new: true }); if (!p) return res.status(404).json({ success: false, message: "Product not found" }); res.json({ success: true, data: normalize(p) }); } catch (e) { res.status(422).json({ success: false, message: e.message }); } };
export const updateProductImages = async (req, res) => { try { if (!Array.isArray(req.body.images)) return res.status(422).json({ success: false, message: "images must be an array" }); const images = req.body.images.filter(x => typeof x === "string" && x.trim()); const p = await Product.findOneAndUpdate({ $or: [{ productId: req.params.id }, { _id: req.params.id }] }, { images, $push: { activityLog: { action: "Product images updated", user: req.body.user || "Admin" } } }, { new: true }); if (!p) return res.status(404).json({ success: false, message: "Product not found" }); res.json({ success: true, data: p.images }); } catch (e) { res.status(422).json({ success: false, message: e.message }); } };
