import Product from "../models/Product.js";

// const findProduct = (id) => Product.findOne({ $or: [{ productId: id }, { _id: id }] });
const findProduct = (id) => Product.findOne({ productId: id });
const save = async (product, action, data) => { product.activityLog.push({ action, user: data.createdBy || data.updatedBy || "Admin", remarks: data.remarks || "" }); await product.save(); return product; };

export const getAvailabilityCalendar = async (req, res) => { try { const p = await findProduct(req.params.id); if (!p) return res.status(404).json({ success: false, message: "Product not found" }); res.json({ success: true, data: { blockedDates: p.blockedDates || [], bookingHistory: p.bookingHistory || [], externalBookings: p.externalBookings || [], cleaningBufferDays: p.cleaningBufferDays || 0 } }); } catch (e) { res.status(500).json({ success: false, message: e.message }); } };
export const addBlockedDate = async (req, res) => { try { const p = await findProduct(req.params.id); if (!p) return res.status(404).json({ success: false, message: "Product not found" }); const { from, to, reason } = req.body; if (!from || !to || !reason || new Date(to) < new Date(from)) return res.status(422).json({ success: false, message: "Valid from date, to date and reason are required" }); if ((p.blockedDates || []).some((b) => new Date(from) <= new Date(b.to) && new Date(to) >= new Date(b.from))) return res.status(409).json({ success: false, message: "Blocked date range overlaps an existing range" }); p.blockedDates.push({ from, to, reason }); await save(p, "Blocked dates added", req.body); res.status(201).json({ success: true, data: p.blockedDates.at(-1) }); } catch (e) { res.status(400).json({ success: false, message: e.message }); } };
export const removeBlockedDate = async (req, res) => { try { const p = await findProduct(req.params.id); if (!p) return res.status(404).json({ success: false, message: "Product not found" }); const index = Number(req.params.index); if (!Number.isInteger(index) || index < 0 || index >= p.blockedDates.length) return res.status(404).json({ success: false, message: "Blocked range not found" }); p.blockedDates.splice(index, 1); await save(p, "Blocked dates removed", req.body || {}); res.json({ success: true, data: p.blockedDates }); } catch (e) { res.status(400).json({ success: false, message: e.message }); } };
export const getProductActivity = async (req, res) => { try { const p = await findProduct(req.params.id); if (!p) return res.status(404).json({ success: false, message: "Product not found" }); res.json({ success: true, data: p.activityLog || [] }); } catch (e) { res.status(500).json({ success: false, message: e.message }); } };
export const getProductPayoutHistory = async (req, res) => { try { const p = await findProduct(req.params.id); if (!p) return res.status(404).json({ success: false, message: "Product not found" }); const Payout = (await import("../models/Payout.js")).default; const rows = await Payout.find({ productName: p.name }).sort({ dueDate: -1 }); res.json({ success: true, data: rows }); } catch (e) { res.status(500).json({ success: false, message: e.message }); } };
export const updateRelatedProducts = async (req, res) => { try { const p = await findProduct(req.params.id); if (!p) return res.status(404).json({ success: false, message: "Product not found" }); if (!Array.isArray(req.body.relatedProductIds)) return res.status(422).json({ success: false, message: "relatedProductIds must be an array" }); const ids = [...new Set(req.body.relatedProductIds.filter((id) => id !== p.productId))]; const count = await Product.countDocuments({ productId: { $in: ids } }); if (count !== ids.length) return res.status(422).json({ success: false, message: "One or more related products do not exist" }); p.relatedProductIds = ids; await save(p, "Related products updated", req.body); res.json({ success: true, data: ids }); } catch (e) { res.status(400).json({ success: false, message: e.message }); } };
export const updateProductLister = async (req, res) => { try { const Lister = (await import("../models/Lister.js")).default; const p = await findProduct(req.params.id); if (!p) return res.status(404).json({ success: false, message: "Product not found" }); const l = await Lister.findOne({ listerId: req.body.listerId }); if (!l) return res.status(404).json({ success: false, message: "Lister not found" }); p.listerId = l.listerId; p.listerName = l.name; if (req.body.payoutPercentage != null) { const rate = Number(req.body.payoutPercentage); if (rate < 0 || rate > 100) return res.status(422).json({ success: false, message: "Payout percentage must be between 0 and 100" }); p.payoutPercentage = rate; } await save(p, "Product lister mapping updated", req.body); res.json({ success: true, data: { listerId: p.listerId, listerName: p.listerName, payoutPercentage: p.payoutPercentage } }); } catch (e) { res.status(422).json({ success: false, message: e.message }); } };
export const addExternalBooking = async (req, res) => { try { const p = await findProduct(req.params.id); if (!p) return res.status(404).json({ success: false, message: "Product not found" }); const { orderId, customerName, startDate, endDate, status = "Confirmed", amount = 0 } = req.body; if (!orderId || !customerName || !startDate || !endDate || new Date(endDate) < new Date(startDate)) return res.status(422).json({ success: false, message: "Order, customer and valid booking dates are required" }); if ((p.externalBookings || []).some(b => b.startDate <= endDate && b.endDate >= startDate && !["Cancelled", "Rejected"].includes(b.status))) return res.status(409).json({ success: false, message: "External booking overlaps an existing booking" }); p.externalBookings.push({ orderId, customerName, startDate, endDate, date: startDate, status, amount, source: "External" }); await save(p, "External booking added", req.body); res.status(201).json({ success: true, data: p.externalBookings.at(-1) }); } catch (e) { res.status(422).json({ success: false, message: e.message }); } };
