import { CalendarEvent, DispatchCard } from './types';

// Replace with real data from your API. Shaped to match the current design reference (March 2026).
export const mockEvents: CalendarEvent[] = [
  {
    id: 'e1',
    type: 'prep-dispatch',
    title: 'Prep dispatch — Crimson Zardozi Bridal …',
    date: '2026-03-11',
    orderId: 'HOK-ORD-001',
    detail: {
      customerName: 'Priya Rathore',
      customerLocation: 'Mumbai',
      customerPhone: '+91 98200 11234',
      orderPlaced: '05 Mar 2026',
      productName: 'Crimson Zardozi Bridal Lehenga',
      productSubtitle: 'Sabyasachi · Size M · Rental',
      rentalPeriodLabel: '13 Mar 2026 – 16 Mar 2026',
      dispatchByLabel: '12 Mar 2026',
      carrierLabel: 'DHL · pending pickup',
      rentalAmountLabel: '₹18,500 + ₹3,330 GST',
      securityDepositLabel: '₹25,000',
      depositStatusLabel: 'Not yet collected',
    },
  },
  {
    id: 'e2',
    type: 'dispatched',
    title: 'Dispatched — Champagne Tissue Sharara',
    date: '2026-03-17',
    orderId: 'HOK-ORD-015',
    detail: {
      customerName: 'Nisha Agarwal',
      customerLocation: 'Mumbai',
      customerPhone: '+91 98330 55217',
      orderPlaced: '15 Mar 2026',
      productName: 'Champagne Tissue Sharara',
      productSubtitle: 'Ritu Kumar · Size M · Rental',
      rentalPeriodLabel: '19 Mar 2026 – 21 Mar 2026',
      dispatchByLabel: '17 Mar 2026',
      dispatchOverdue: true,
      carrierLabel: 'Delhivery · DEL66119004IN',
      rentalAmountLabel: '₹5,500 + ₹990 GST',
      securityDepositLabel: '₹12,000',
      depositStatusLabel: 'Held — awaiting release',
      overdueMessage: 'Piece not yet dispatched. Action required immediately.',
    },
  },
  {
    id: 'e3',
    type: 'dispatched',
    title: 'Dispatched — Rajputana Silk Bridal Lehe…',
    date: '2026-03-18',
    orderId: 'HOK-ORD-020',
    detail: {
      customerName: 'Kabir Malhotra',
      customerLocation: 'Thane',
      customerPhone: '+91 99870 44210',
      orderPlaced: '12 Mar 2026',
      productName: 'Rajputana Silk Bridal Lehenga',
      productSubtitle: 'Anita Dongre · Size L · Rental',
      rentalPeriodLabel: '19 Mar 2026 – 23 Mar 2026',
      dispatchByLabel: '18 Mar 2026',
      carrierLabel: 'DHL · DHL77321098IN',
      rentalAmountLabel: '₹22,000 + ₹3,960 GST',
      securityDepositLabel: '₹30,000',
      depositStatusLabel: 'Held — awaiting release',
    },
  },
  {
    id: 'e4',
    type: 'prep-dispatch',
    title: 'Prep dispatch — Rose Georgette Anarkali',
    date: '2026-03-18',
    orderId: 'HOK-ORD-003',
    detail: {
      customerName: 'Neha Kulkarni',
      customerLocation: 'Navi Mumbai',
      customerPhone: '+91 98670 33221',
      orderPlaced: '10 Mar 2026',
      productName: 'Rose Georgette Anarkali',
      productSubtitle: 'Manish Malhotra · Size S · Rental',
      rentalPeriodLabel: '20 Mar 2026 – 22 Mar 2026',
      dispatchByLabel: '20 Mar 2026',
      carrierLabel: 'Delhivery · pending pickup',
      rentalAmountLabel: '₹7,200 + ₹1,296 GST',
      securityDepositLabel: '₹10,000',
      depositStatusLabel: 'Not yet collected',
    },
  },
  {
    id: 'e5',
    type: 'return-due',
    title: 'Return due — Crimson Zardozi Bridal Leh…',
    date: '2026-03-18',
    orderId: 'HOK-ORD-001',
    detail: {
      customerName: 'Priya Rathore',
      customerLocation: 'Mumbai',
      customerPhone: '+91 98200 11234',
      orderPlaced: '05 Mar 2026',
      productName: 'Crimson Zardozi Bridal Lehenga',
      productSubtitle: 'Sabyasachi · Size M · Rental',
      rentalPeriodLabel: '13 Mar 2026 – 18 Mar 2026',
      dispatchByLabel: '12 Mar 2026',
      carrierLabel: 'DHL · DHL55021871IN',
      rentalAmountLabel: '₹18,500 + ₹3,330 GST',
      securityDepositLabel: '₹25,000',
      depositStatusLabel: 'Held — pending return inspection',
    },
  },
  {
    id: 'e6',
    type: 'internal-task',
    title: 'Call tailor re: beading repair',
    date: '2026-03-19',
    detail: {
      customerName: 'Internal task',
      customerLocation: 'Workroom',
      customerPhone: '—',
      orderPlaced: '—',
      productName: 'Beading repair — tailor follow-up',
      productSubtitle: 'Internal task · No customer attached',
      rentalPeriodLabel: '—',
      dispatchByLabel: '—',
      carrierLabel: '—',
      rentalAmountLabel: '—',
      securityDepositLabel: '—',
      depositStatusLabel: '—',
    },
  },
  {
    id: 'e7',
    type: 'cleaning',
    title: 'Cleaning — Crimson Zardozi …',
    date: '2026-03-19',
    orderId: 'HOK-ORD-001',
    detail: {
      customerName: 'Priya Rathore',
      customerLocation: 'Mumbai',
      customerPhone: '+91 98200 11234',
      orderPlaced: '05 Mar 2026',
      productName: 'Crimson Zardozi Bridal Lehenga',
      productSubtitle: 'Sabyasachi · Size M · Post-rental cleaning',
      rentalPeriodLabel: '13 Mar 2026 – 18 Mar 2026',
      dispatchByLabel: '—',
      carrierLabel: 'In-house cleaning',
      rentalAmountLabel: '₹18,500 + ₹3,330 GST',
      securityDepositLabel: '₹25,000',
      depositStatusLabel: 'Held — pending cleaning sign-off',
    },
  },
  {
    id: 'e8',
    type: 'rental-starts',
    title: 'Rental starts — Nisha Agarw…',
    date: '2026-03-19',
    orderId: 'HOK-ORD-015',
    detail: {
      customerName: 'Nisha Agarwal',
      customerLocation: 'Mumbai',
      customerPhone: '+91 98330 55217',
      orderPlaced: '15 Mar 2026',
      productName: 'Champagne Tissue Sharara',
      productSubtitle: 'Ritu Kumar · Size M · Rental',
      rentalPeriodLabel: '19 Mar 2026 – 21 Mar 2026',
      dispatchByLabel: '17 Mar 2026',
      carrierLabel: 'Delhivery · DEL66119004IN',
      rentalAmountLabel: '₹5,500 + ₹990 GST',
      securityDepositLabel: '₹12,000',
      depositStatusLabel: 'Held — awaiting release',
    },
  },
  {
    id: 'e9',
    type: 'dispatched',
    title: 'Dispatched — Crimson Zardozi Bridal Le…',
    date: '2026-03-23',
    orderId: 'HOK-ORD-916',
    detail: {
      customerName: 'Kabir Malhotra',
      customerLocation: 'Thane',
      customerPhone: '+91 99870 44210',
      orderPlaced: '18 Mar 2026',
      productName: 'Crimson Zardozi Bridal Lehenga',
      productSubtitle: 'Sabyasachi · Size L · Rental',
      rentalPeriodLabel: '23 Mar 2026 – 26 Mar 2026',
      dispatchByLabel: '23 Mar 2026',
      carrierLabel: 'DHL · courier and tracking confirmed',
      rentalAmountLabel: '₹18,500 + ₹3,330 GST',
      securityDepositLabel: '₹25,000',
      depositStatusLabel: 'Held — awaiting release',
    },
  },
  {
    id: 'e10',
    type: 'cleaning',
    title: 'Cleaning — Rajputana Silk Bridal Lehenga',
    date: '2026-03-23',
    orderId: 'HOK-ORD-020',
    detail: {
      customerName: 'Kabir Malhotra',
      customerLocation: 'Thane',
      customerPhone: '+91 99870 44210',
      orderPlaced: '12 Mar 2026',
      productName: 'Rajputana Silk Bridal Lehenga',
      productSubtitle: 'Anita Dongre · Size L · Post-rental cleaning',
      rentalPeriodLabel: '19 Mar 2026 – 23 Mar 2026',
      dispatchByLabel: '—',
      carrierLabel: 'In-house cleaning',
      rentalAmountLabel: '₹22,000 + ₹3,960 GST',
      securityDepositLabel: '₹30,000',
      depositStatusLabel: 'Held — pending cleaning sign-off',
    },
  },
  {
    id: 'e11',
    type: 'dispatched',
    title: 'Dispatched — Rose Georgette Anarkali',
    date: '2026-03-24',
    orderId: 'HOK-ORD-913',
    detail: {
      customerName: 'Ananya Desai',
      customerLocation: 'Mumbai',
      customerPhone: '+91 98450 12987',
      orderPlaced: '20 Mar 2026',
      productName: 'Rose Georgette Anarkali',
      productSubtitle: 'Manish Malhotra · Size S · 1-day rental',
      rentalPeriodLabel: '24 Mar 2026 – 25 Mar 2026',
      dispatchByLabel: '24 Mar 2026',
      carrierLabel: 'Delhivery · dispatch for mehendi function',
      rentalAmountLabel: '₹6,000 + ₹1,080 GST',
      securityDepositLabel: '₹10,000',
      depositStatusLabel: 'Held — awaiting release',
    },
  },
  {
    id: 'e12',
    type: 'dispatched',
    title: 'Dispatched — Champagne Tissue Sharara',
    date: '2026-03-24',
    orderId: 'HOK-ORD-015',
    detail: {
      customerName: 'Nisha Agarwal',
      customerLocation: 'Mumbai',
      customerPhone: '+91 98330 55217',
      orderPlaced: '15 Mar 2026',
      productName: 'Champagne Tissue Sharara',
      productSubtitle: 'Ritu Kumar · Size M · Rental',
      rentalPeriodLabel: '24 Mar 2026 – 26 Mar 2026',
      dispatchByLabel: '24 Mar 2026',
      carrierLabel: 'Delhivery · DEL66119112IN',
      rentalAmountLabel: '₹5,500 + ₹990 GST',
      securityDepositLabel: '₹12,000',
      depositStatusLabel: 'Held — awaiting release',
    },
  },
  {
    id: 'e13',
    type: 'prep-dispatch',
    title: 'Prep dispatch — Gulabi Lehenga + Sharara',
    date: '2026-03-24',
    orderId: 'HOK-ORD-905',
    detail: {
      customerName: 'Divya Nair',
      customerLocation: 'Mumbai',
      customerPhone: '+91 98200 76543',
      orderPlaced: '19 Mar 2026',
      productName: 'Gulabi Lehenga + Sharara',
      productSubtitle: '2-piece set · Size M · Rental',
      rentalPeriodLabel: '26 Mar 2026 – 28 Mar 2026',
      dispatchByLabel: '26 Mar 2026',
      carrierLabel: 'Delhivery · pending pickup',
      rentalAmountLabel: '₹9,800 + ₹1,764 GST',
      securityDepositLabel: '₹15,000',
      depositStatusLabel: 'Not yet collected',
    },
  },
  {
    id: 'e14',
    type: 'return-due',
    title: 'Return due — extra 1',
    date: '2026-03-24',
    detail: {
      customerName: 'Meera Kapoor',
      customerLocation: 'Mumbai',
      customerPhone: '+91 98330 22114',
      orderPlaced: '15 Mar 2026',
      productName: 'Extra return item 1',
      productSubtitle: 'Placeholder · Size — · Rental',
      rentalPeriodLabel: '20 Mar 2026 – 24 Mar 2026',
      dispatchByLabel: '—',
      carrierLabel: '—',
      rentalAmountLabel: '—',
      securityDepositLabel: '—',
      depositStatusLabel: 'Pending return',
    },
  },
  {
    id: 'e15',
    type: 'deposit-due',
    title: 'Return due — extra 2',
    date: '2026-03-24',
    detail: {
      customerName: 'Sanya Bhatt',
      customerLocation: 'Mumbai',
      customerPhone: '+91 98670 88321',
      orderPlaced: '16 Mar 2026',
      productName: 'Extra deposit item 2',
      productSubtitle: 'Placeholder · Size — · Rental',
      rentalPeriodLabel: '21 Mar 2026 – 24 Mar 2026',
      dispatchByLabel: '—',
      carrierLabel: '—',
      rentalAmountLabel: '—',
      securityDepositLabel: '₹8,000',
      depositStatusLabel: 'Deposit collection due',
    },
  },
  {
    id: 'e16',
    type: 'payout-due',
    title: 'Return due — extra 3',
    date: '2026-03-24',
    detail: {
      customerName: 'Ritika Shah',
      customerLocation: 'Mumbai',
      customerPhone: '+91 98450 99213',
      orderPlaced: '14 Mar 2026',
      productName: 'Extra payout item 3',
      productSubtitle: 'Placeholder · Size — · Rental',
      rentalPeriodLabel: '19 Mar 2026 – 24 Mar 2026',
      dispatchByLabel: '—',
      carrierLabel: '—',
      rentalAmountLabel: '₹6,500',
      securityDepositLabel: '—',
      depositStatusLabel: 'Payout due to vendor',
    },
  },
  {
    id: 'e17',
    type: 'offer-response-due',
    title: 'Return due — extra 4',
    date: '2026-03-24',
    detail: {
      customerName: 'Tanvi Joshi',
      customerLocation: 'Mumbai',
      customerPhone: '+91 98200 44567',
      orderPlaced: '17 Mar 2026',
      productName: 'Extra offer item 4',
      productSubtitle: 'Placeholder · Size — · Rental',
      rentalPeriodLabel: '22 Mar 2026 – 24 Mar 2026',
      dispatchByLabel: '—',
      carrierLabel: '—',
      rentalAmountLabel: '—',
      securityDepositLabel: '—',
      depositStatusLabel: 'Awaiting customer response',
    },
  },
  {
    id: 'e18',
    type: 'prep-dispatch',
    title: 'Prep dispatch — Crimson Zardozi Bridal …',
    date: '2026-03-25',
    orderId: 'HOK-ORD-912',
    detail: {
      customerName: 'Meera Kapoor',
      customerLocation: 'Mumbai',
      customerPhone: '+91 98330 22114',
      orderPlaced: '22 Mar 2026',
      productName: 'Crimson Zardozi Bridal Lehenga',
      productSubtitle: 'Sabyasachi · Size M · Rental',
      rentalPeriodLabel: '27 Mar 2026 – 30 Mar 2026',
      dispatchByLabel: '27 Mar 2026',
      carrierLabel: 'DHL · pending pickup',
      rentalAmountLabel: '₹18,500 + ₹3,330 GST',
      securityDepositLabel: '₹25,000',
      depositStatusLabel: 'Not yet collected',
      overdueMessage: "Booking overlaps HOK-ORD-010's rental + cleaning window.",
    },
  },
  {
    id: 'e19',
    type: 'return-due',
    title: 'Return due — Rose Georgette Anarkali',
    date: '2026-03-25',
    orderId: 'HOK-ORD-893',
    detail: {
      customerName: 'Neha Kulkarni',
      customerLocation: 'Navi Mumbai',
      customerPhone: '+91 98670 33221',
      orderPlaced: '20 Mar 2026',
      productName: 'Rose Georgette Anarkali',
      productSubtitle: 'Manish Malhotra · Size S · Rental',
      rentalPeriodLabel: '20 Mar 2026 – 25 Mar 2026',
      dispatchByLabel: '—',
      carrierLabel: 'Delhivery · DEL66119045IN',
      rentalAmountLabel: '₹7,200 + ₹1,296 GST',
      securityDepositLabel: '₹10,000',
      depositStatusLabel: 'Held — pending return inspection',
    },
  },
  {
    id: 'e20',
    type: 'return-due',
    title: 'Return due — Rose Georgette Anarkali',
    date: '2026-03-25',
    orderId: 'HOK-ORD-913',
    detail: {
      customerName: 'Ananya Desai',
      customerLocation: 'Mumbai',
      customerPhone: '+91 98450 12987',
      orderPlaced: '20 Mar 2026',
      productName: 'Rose Georgette Anarkali',
      productSubtitle: 'Manish Malhotra · Size S · 1-day rental',
      rentalPeriodLabel: '24 Mar 2026 – 25 Mar 2026',
      dispatchByLabel: '—',
      carrierLabel: 'Delhivery · DEL66119112IN',
      rentalAmountLabel: '₹6,000 + ₹1,080 GST',
      securityDepositLabel: '₹10,000',
      depositStatusLabel: 'Held — pending return inspection',
    },
  },
  {
    id: 'e21',
    type: 'cleaning',
    title: 'extra 1',
    date: '2026-03-25',
    detail: {
      customerName: 'Rhea Choudhary',
      customerLocation: 'Mumbai',
      customerPhone: '+91 98330 71120',
      orderPlaced: '18 Mar 2026',
      productName: 'Extra cleaning item',
      productSubtitle: 'Placeholder · Size — · Post-rental cleaning',
      rentalPeriodLabel: '20 Mar 2026 – 25 Mar 2026',
      dispatchByLabel: '—',
      carrierLabel: 'In-house cleaning',
      rentalAmountLabel: '—',
      securityDepositLabel: '—',
      depositStatusLabel: 'Held — pending cleaning sign-off',
    },
  },
  {
    id: 'e22',
    type: 'back-in-rotation',
    title: 'extra 2',
    date: '2026-03-25',
    detail: {
      customerName: 'Ishita Verma',
      customerLocation: 'Mumbai',
      customerPhone: '+91 98450 66234',
      orderPlaced: '16 Mar 2026',
      productName: 'Extra back-in-rotation item',
      productSubtitle: 'Placeholder · Size — · Cleaned and re-stocked',
      rentalPeriodLabel: '—',
      dispatchByLabel: '—',
      carrierLabel: '—',
      rentalAmountLabel: '—',
      securityDepositLabel: '—',
      depositStatusLabel: 'Deposit released',
    },
  },
  {
    id: 'e23',
    type: 'dispatched',
    title: 'Dispatched — Gulabi Lehenga …',
    date: '2026-03-26',
    orderId: 'HOK-ORD-905',
    detail: {
      customerName: 'Divya Nair',
      customerLocation: 'Mumbai',
      customerPhone: '+91 98200 76543',
      orderPlaced: '19 Mar 2026',
      productName: 'Gulabi Lehenga + Sharara',
      productSubtitle: '2-piece set · Size M · Rental',
      rentalPeriodLabel: '26 Mar 2026 – 28 Mar 2026',
      dispatchByLabel: '26 Mar 2026',
      carrierLabel: 'Delhivery · 2-piece dispatch',
      rentalAmountLabel: '₹9,800 + ₹1,764 GST',
      securityDepositLabel: '₹15,000',
      depositStatusLabel: 'Held — awaiting release',
    },
  },
  {
    id: 'e24',
    type: 'prep-dispatch',
    title: 'Prep dispatch — Rose George…',
    date: '2026-03-26',
    orderId: 'HOK-ORD-930',
    detail: {
      customerName: 'Aisha Merchant',
      customerLocation: 'Mumbai',
      customerPhone: '+91 98200 33998',
      orderPlaced: '21 Mar 2026',
      productName: 'Rose Georgette Anarkali',
      productSubtitle: 'Manish Malhotra · Size M · Rental',
      rentalPeriodLabel: '28 Mar 2026 – 30 Mar 2026',
      dispatchByLabel: '28 Mar 2026',
      carrierLabel: 'Delhivery · pending pickup',
      rentalAmountLabel: '₹7,200 + ₹1,296 GST',
      securityDepositLabel: '₹10,000',
      depositStatusLabel: 'Not yet collected',
    },
  },
  {
    id: 'e25',
    type: 'internal-task',
    title: 'Restock garment bags & tissu…',
    date: '2026-03-26',
    detail: {
      customerName: 'Internal task',
      customerLocation: 'Workroom',
      customerPhone: '—',
      orderPlaced: '—',
      productName: 'Restock garment bags & tissue paper',
      productSubtitle: 'Internal task · No customer attached',
      rentalPeriodLabel: '—',
      dispatchByLabel: '—',
      carrierLabel: '—',
      rentalAmountLabel: '—',
      securityDepositLabel: '—',
      depositStatusLabel: '—',
    },
  },
  {
    id: 'e26',
    type: 'offer-response-due',
    title: 'Offer response due — Gulabi Silk Bridal L…',
    date: '2026-03-30',
    detail: {
      customerName: 'Sneha Iyer',
      customerLocation: 'Mumbai',
      customerPhone: '+91 98670 55432',
      orderPlaced: '24 Mar 2026',
      productName: 'Gulabi Silk Bridal Lehenga',
      productSubtitle: 'Sabyasachi · Size M · Rental offer',
      rentalPeriodLabel: 'Proposed 02 Apr 2026 – 05 Apr 2026',
      dispatchByLabel: '—',
      carrierLabel: '—',
      rentalAmountLabel: '₹19,500 + ₹3,510 GST',
      securityDepositLabel: '₹25,000',
      depositStatusLabel: 'Awaiting customer response',
    },
  },
  {
    id: 'e27',
    type: 'delivery-followup',
    title: 'Crimson Zardozi Bridal Lehenga back in r…',
    date: '2026-03-31',
    orderId: 'HOK-ORD-001',
    detail: {
      customerName: 'Priya Rathore',
      customerLocation: 'Mumbai',
      customerPhone: '+91 98200 11234',
      orderPlaced: '05 Mar 2026',
      productName: 'Crimson Zardozi Bridal Lehenga',
      productSubtitle: 'Sabyasachi · Size M · Cleaned and re-stocked',
      rentalPeriodLabel: '13 Mar 2026 – 18 Mar 2026',
      dispatchByLabel: '—',
      carrierLabel: '—',
      rentalAmountLabel: '₹18,500 + ₹3,330 GST',
      securityDepositLabel: '₹25,000',
      depositStatusLabel: 'Deposit released',
    },
  },
];

export const mockDispatches: DispatchCard[] = [
  {
    id: 'd1',
    dateLabel: '13 MAR',
    title: 'Crimson Zardozi Bridal Lehenga',
    subtitle: 'Priya Rathore · Dispatch via DHL',
    orderId: 'HOK-ORD-881',
  },
  {
    id: 'd2',
    dateLabel: '20 MAR',
    title: 'Rose Georgette Anarkali',
    subtitle: 'Neha Kulkarni · Dispatch via Delhivery',
    orderId: 'HOK-ORD-893',
  },
  {
    id: 'd3',
    dateLabel: '26 MAR',
    title: 'Gulabi Lehenga + Sharara',
    subtitle: 'Divya Nair · 2-piece dispatch',
    orderId: 'HOK-ORD-905',
  },
  {
    id: 'd4',
    dateLabel: 'TODAY — 23 MAR',
    isToday: true,
    title: 'Crimson Zardozi Bridal Lehenga',
    subtitle: 'Kabir Malhotra · Dispatch via DHL — courier and tracking already confirmed.',
    orderId: 'HOK-ORD-916',
  },
  {
    id: 'd5',
    dateLabel: '27 MAR',
    title: 'Crimson Zardozi Bridal Lehenga',
    subtitle: "Meera Kapoor · Scheduled dispatch — booking overlaps HOK-ORD-010's rental + cleaning window.",
    orderId: 'HOK-ORD-912',
  },
  {
    id: 'd6',
    dateLabel: '24 MAR',
    title: 'Rose Georgette Anarkali',
    subtitle: 'Ananya Desai · Dispatch via Delhivery — 1-day rental for a mehendi function.',
    orderId: 'HOK-ORD-913',
  },
];